#    ██╗  ██╗     ███╗   ███╗ █████╗ ███████╗        ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗
#    ╚██╗██╔╝     ████╗ ████║██╔══██╗██╔════╝       ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝
#     ╚███╔╝█████╗██╔████╔██║███████║███████╗  ███  ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
#     ██╔██╗╚════╝██║╚██╔╝██║██╔══██║╚════██║       ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
#    ██╔╝ ██╗     ██║ ╚═╝ ██║██║  ██║███████║       ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#    ╚═╝  ╚═╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝        ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝

maximum-players: 100

lobby-spawn-point:
  world: "world"
  x: 50
  y: 100
  z: 50
  pitch: 0.0
  yaw: 0.0

contributors:
  # Format: <Minecraft IGN><Contribution><X, Y, Z> # Yes, with the "<" and ">"
  # Example: <Notch><Creator of Minecraft><150, 64, 150>
  - "<Notch><Creator of Minecraft><0, 0, 0>"
  - "<jeb_><CCO of Mojang><0, 0, 0>"