name: ChristmasEventPlugin
version: 1.0
main: gg.flyte.christmas.ChristmasEventPlugin
api-version: '1.21'
description: Flyte x Carbon Christmas Event Plugin!
authors: [Shreyas, Stephen, Josh, Dawson, Atom, Brandon, Dan]
website: https://carbon.christmas